# syntax=docker/dockerfile:1
#
# Multi-stage build. pjsua2 (the PJSIP Python bindings) has no official PyPI
# wheel worth trusting for this project's deployment target (see README), so
# this builder stage compiles pjproject + its SWIG Python bindings from
# source, following PJSIP's own documented build method. Both stages are
# pinned to the same Debian release ("bookworm") so the compiled _pjsua2
# extension stays ABI-compatible with the runtime stage's libssl/libstdc++.

FROM python:3.12-bookworm AS pjsip-builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    swig \
    git \
    ca-certificates \
    libssl-dev \
    libasound2-dev \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

ARG PJPROJECT_VERSION=2.15.1
RUN git clone --branch ${PJPROJECT_VERSION} --depth 1 \
    https://github.com/pjsip/pjproject.git /pjproject

WORKDIR /pjproject
RUN echo "export CFLAGS += -fPIC" > user.mak \
 && ./configure --disable-video \
 && make dep \
 && make -j"$(nproc)"

WORKDIR /pjproject/pjsip-apps/src/swig/python
# Python 3.12 dropped distutils from the stdlib, and setup.py (generated by
# pjproject's own build) still imports it as a fallback when setuptools is
# missing entirely -- so setuptools must be installed explicitly first.
RUN pip install --no-cache-dir setuptools wheel \
 && make \
 && python3 setup.py bdist_wheel -d /wheels


FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl3 \
    libasound2 \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=pjsip-builder /wheels /wheels
COPY requirements.txt .
RUN pip install --no-cache-dir /wheels/*.whl -r requirements.txt

COPY app ./app

# UID/GID pinned (not left to "next available") so it's a documented,
# stable contract: docker-compose.yml bind-mounts ./data:/app/data for
# log persistence, and that host directory must be chown'd to this same
# uid:gid beforehand (see README) since this container never runs as root.
RUN groupadd -g 1000 appuser && useradd -m -u 1000 -g 1000 appuser \
 && mkdir -p /app/data /app/config \
 && chown -R appuser:appuser /app/data /app/config
USER appuser

ENV CONFIG_FILE=/app/config/app.env
ENV DATA_DIR=/app/data
EXPOSE 8080

# app/healthcheck.py resolves the actual HTTP_PORT the same way app/main.py
# does (OS env wins, else read it out of the mounted secrets file) so this
# check works correctly regardless of where HTTP_PORT was overridden.
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s \
  CMD python -m app.healthcheck || exit 1

CMD ["python", "-m", "app.main"]
